[package]
name = "capntproto-quality"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
capntproto-test-support = { path = "../test-support" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
fs2 = "0.4"
plotters = { version = "=0.3.7", default-features = false, features = ["svg_backend"] }
