[package]
name = "reproto-storage-comparison"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
reproto = { path = "../..", default-features = false, features = ["storage"] }
eae_pages = { path = "../../target/eae-benchmark/eae-research/rust" }
serde_json = "1"
tempfile = "3"
capnp = { path = "../../vendor/capnp" }

[build-dependencies]
capnpc = { path = "../../vendor/capnpc" }

[profile.release]
debug = 1
